In [338]:
import pandas as pd

# Load the CSV file
file_path = 'Resources/2013_to_2023_property-sales-data.csv'  
data = pd.read_csv(file_path)

C:\Users\ebehnia\AppData\Local\Temp\ipykernel_18508\1787498791.py:5: DtypeWarning: Columns (12,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

In [339]:
# Defining the data types for the problematic columns
dtype_dict = {
    'FinishedSqft': 'str',
    'Lotsize': 'str',
    'Sale_price': 'str'
}

data = pd.read_csv(file_path)

C:\Users\ebehnia\AppData\Local\Temp\ipykernel_18508\4185461838.py:8: DtypeWarning: Columns (12,17,19) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

In [340]:
# Function to clean numeric columns
def clean_numeric(column):
    # Ensure the column is a string, replace unwanted characters, and convert to numeric
    return pd.to_numeric(column.astype(str).str.replace('[\$,]', '', regex=True).str.replace(',', ''), errors='coerce')

In [341]:
# Cleaning and converting the 'FinishedSqft', 'Lotsize', and 'Sale_price' columns
data['FinishedSqft'] = clean_numeric(data['FinishedSqft'])
data['Lotsize'] = clean_numeric(data['Lotsize'])
data['Sale_price'] = clean_numeric(data['Sale_price'])
data

,PropertyID,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,98459.0,Commercial,30091000,9220 N 107TH ST,NaN,9.0,6202.0,Office Building - 1 Story,Concrete Block,1.0,1981.0,NaN,12960.0,5,NaN,0.0,0.0,54885.0,2023-08-15,530000.0
1,98477.0,Residential,39995000,9574 N 107TH ST,NaN,9.0,40.0,Cape Cod,Aluminum/Vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0
2,98500.0,Residential,40071000,9531 N MICHAEL CT,NaN,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0
3,98566.0,Residential,50047000,9350 N JOYCE AV,NaN,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0
4,98598.0,Residential,50079000,9355 N BURBANK AV,NaN,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,NaN,Commercial,4280769100,106 W SEEBOTH ST,NaN,12.0,6275.0,"Store Building - Single tenant, 1 story",NaN,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,Dec-13,203000.0
56228,NaN,Commercial,5000407000,2659 S KINNICKINNIC AV,NaN,14.0,6282.0,Tavern,NaN,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,Dec-13,225000.0
56229,NaN,Commercial,3921041111,417 E CHICAGO ST,NaN,4.0,6296.0,Warehouse Building - 1 Story,NaN,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,Dec-13,10000000.0
56230,NaN,Commercial,2452125100,4290 N TEUTONIA AV,NaN,1.0,6234.0,Warehouse Building - 1 Story,NaN,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,Dec-13,200000.0
56231,NaN,Vacant Land,1140191000,6885 N 107TH ST,NaN,5.0,820.0,**,NaN,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,Dec-13,25000.0

In [342]:
data.info(type)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56232 entries, 0 to 56231
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PropertyID    32049 non-null  float64
 1   PropType      56224 non-null  object
 2   taxkey        56232 non-null  int64
 3   Address       56228 non-null  object
 4   CondoProject  9164 non-null   object
 5   District      56230 non-null  float64
 6   nbhd          56175 non-null  float64
 7   Style         56141 non-null  object
 8   Extwall       45726 non-null  object
 9   Stories       56063 non-null  float64
 10  Year_Built    56171 non-null  float64
 11  Rooms         54602 non-null  float64
 12  FinishedSqft  56131 non-null  float64
 13  Units         56232 non-null  int64
 14  Bdrms         54603 non-null  float64
 15  Fbath         55577 non-null  float64
 16  Hbath         51392 non-null  float64
 17  Lotsize       56231 non-null  float64
 18  Sale_date     56232 non-null  object
 19  Sale_price    56222 non-null  float64
dtypes: float64(12), int64(2), object(6)
memory usage: 8.6+ MB

In [343]:
# droping columns with unique values b/c they can't be used in machine learning process
data = data.drop(columns=['PropertyID', 'taxkey', 'Address', 'CondoProject'])
data

,PropType,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,Commercial,9.0,6202.0,Office Building - 1 Story,Concrete Block,1.0,1981.0,NaN,12960.0,5,NaN,0.0,0.0,54885.0,2023-08-15,530000.0
1,Residential,9.0,40.0,Cape Cod,Aluminum/Vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0
2,Residential,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0
3,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0
4,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,Commercial,12.0,6275.0,"Store Building - Single tenant, 1 story",NaN,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,Dec-13,203000.0
56228,Commercial,14.0,6282.0,Tavern,NaN,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,Dec-13,225000.0
56229,Commercial,4.0,6296.0,Warehouse Building - 1 Story,NaN,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,Dec-13,10000000.0
56230,Commercial,1.0,6234.0,Warehouse Building - 1 Story,NaN,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,Dec-13,200000.0
56231,Vacant Land,5.0,820.0,**,NaN,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,Dec-13,25000.0

In [326]:
# Filling in missing needed values
# Most missing Extwall were condos. Filling with brick, since the remaining condos had brick.
data['Extwall'] = data['Extwall'].fillna("brick")
# Filling with 0 for bdrms and rooms
data['Bdrms'] = data['Bdrms'].fillna(0.0)
data['Rooms'] = data['Rooms'].fillna(0.0)
# Filling with 1 for stories
data['Stories'] = data['Stories'].fillna(1.0)
data

,PropType,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,Commercial,9.0,6202.0,Office Building - 1 Story,Concrete Block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0
1,Residential,9.0,40.0,Cape Cod,Aluminum/Vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0
2,Residential,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0
3,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0
4,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,Commercial,12.0,6275.0,"Store Building - Single tenant, 1 story",brick,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,Dec-13,203000.0
56228,Commercial,14.0,6282.0,Tavern,brick,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,Dec-13,225000.0
56229,Commercial,4.0,6296.0,Warehouse Building - 1 Story,brick,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,Dec-13,10000000.0
56230,Commercial,1.0,6234.0,Warehouse Building - 1 Story,brick,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,Dec-13,200000.0
56231,Vacant Land,5.0,820.0,**,brick,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,Dec-13,25000.0

In [328]:

# Converting 'Sale_date' to datetime with mixed format and adding sale-year and sale-month columns 
data['Sale_date'] = pd.to_datetime(data['Sale_date'], errors='coerce')
data['sale_year'] = data['Sale_date'].dt.year
data['sale_month'] = data['Sale_date'].dt.month
data

,PropType,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,sale_year,sale_month
0,Commercial,9.0,6202.0,Office Building - 1 Story,Concrete Block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,Residential,9.0,40.0,Cape Cod,Aluminum/Vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,Residential,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,Commercial,12.0,6275.0,"Store Building - Single tenant, 1 story",brick,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,NaT,203000.0,NaN,NaN
56228,Commercial,14.0,6282.0,Tavern,brick,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,NaT,225000.0,NaN,NaN
56229,Commercial,4.0,6296.0,Warehouse Building - 1 Story,brick,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,NaT,10000000.0,NaN,NaN
56230,Commercial,1.0,6234.0,Warehouse Building - 1 Story,brick,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,NaT,200000.0,NaN,NaN
56231,Vacant Land,5.0,820.0,**,brick,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,NaT,25000.0,NaN,NaN

In [330]:
# Standardizing data
# Standardize column names to lowercase
data.columns = [col.lower() for col in data.columns]
data

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
0,Commercial,9.0,6202.0,Office Building - 1 Story,Concrete Block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,Residential,9.0,40.0,Cape Cod,Aluminum/Vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,Residential,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,Residential,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,Commercial,12.0,6275.0,"Store Building - Single tenant, 1 story",brick,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,NaT,203000.0,NaN,NaN
56228,Commercial,14.0,6282.0,Tavern,brick,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,NaT,225000.0,NaN,NaN
56229,Commercial,4.0,6296.0,Warehouse Building - 1 Story,brick,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,NaT,10000000.0,NaN,NaN
56230,Commercial,1.0,6234.0,Warehouse Building - 1 Story,brick,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,NaT,200000.0,NaN,NaN
56231,Vacant Land,5.0,820.0,**,brick,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,NaT,25000.0,NaN,NaN

In [331]:
# Standardizig categorical columns to consistent capitalization
data['proptype'] = data['proptype'].str.lower()
data['style'] = data['style'].str.lower()
data['extwall'] = data['extwall'].str.lower()
data

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
0,commercial,9.0,6202.0,office building - 1 story,concrete block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,residential,9.0,40.0,cape cod,aluminum/vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,residential,9.0,40.0,ranch,fiber cement/hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56227,commercial,12.0,6275.0,"store building - single tenant, 1 story",brick,1.0,1926.0,0.0,1533.0,1,0.0,0.0,0.0,421.0,NaT,203000.0,NaN,NaN
56228,commercial,14.0,6282.0,tavern,brick,2.0,1906.0,0.0,2880.0,1,0.0,0.0,0.0,3000.0,NaT,225000.0,NaN,NaN
56229,commercial,4.0,6296.0,warehouse building - 1 story,brick,1.0,1964.0,0.0,42141.0,1,0.0,0.0,0.0,91440.0,NaT,10000000.0,NaN,NaN
56230,commercial,1.0,6234.0,warehouse building - 1 story,brick,1.0,1951.0,0.0,11297.0,1,0.0,0.0,0.0,16403.0,NaT,200000.0,NaN,NaN
56231,vacant land,5.0,820.0,**,brick,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,20090.0,NaT,25000.0,NaN,NaN

In [333]:
# Handling Missing Values
# For simplicity, we'll drop rows with missing target values (sale_price) and rows with excessive missing values.
data_cleaned = data.dropna(subset=['sale_price', 'sale_date', 'finishedsqft', 'year_built'])
data_cleaned

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
0,commercial,9.0,6202.0,office building - 1 story,concrete block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,residential,9.0,40.0,cape cod,aluminum/vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,residential,9.0,40.0,ranch,fiber cement/hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12972,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-11,125900.0,2022.0,3.0
12973,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1379.0,1,2.0,1.0,1.0,1.0,2022-10-28,150000.0,2022.0,10.0
12974,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-15,130000.0,2022.0,3.0
12975,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,5.0,1100.0,1,2.0,1.0,1.0,1.0,2022-12-30,123000.0,2022.0,12.0
12976,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1141.0,1,2.0,1.0,1.0,1.0,2022-07-08,157500.0,2022.0,7.0

In [334]:
# Removing Duplicate Records
data_cleaned = data_cleaned.drop_duplicates()
data_cleaned

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
0,commercial,9.0,6202.0,office building - 1 story,concrete block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,residential,9.0,40.0,cape cod,aluminum/vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,residential,9.0,40.0,ranch,fiber cement/hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12972,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-11,125900.0,2022.0,3.0
12973,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1379.0,1,2.0,1.0,1.0,1.0,2022-10-28,150000.0,2022.0,10.0
12974,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-15,130000.0,2022.0,3.0
12975,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,5.0,1100.0,1,2.0,1.0,1.0,1.0,2022-12-30,123000.0,2022.0,12.0
12976,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1141.0,1,2.0,1.0,1.0,1.0,2022-07-08,157500.0,2022.0,7.0

In [335]:
#checking for null values
print(data_cleaned.isnull().sum())

null_rows = data_cleaned[data_cleaned.isnull().any(axis=1)]
null_rows

proptype        0
district        0
nbhd            0
style           0
extwall         0
stories         0
year_built      0
rooms           0
finishedsqft    0
units           0
bdrms           0
fbath           0
hbath           0
lotsize         0
sale_date       0
sale_price      0
sale_year       0
sale_month      0
dtype: int64

Empty DataFrame
Columns: [proptype, district, nbhd, style, extwall, stories, year_built, rooms, finishedsqft, units, bdrms, fbath, hbath, lotsize, sale_date, sale_price, sale_year, sale_month]
Index: []

In [313]:
#investigating null condo extwall entries
#condos = data_cleaned[data_cleaned['proptype'].str.contains("condominium")]
#condos_not_null = condos[condos['extwall'].notnull()]
#condos_not_null

#extwall = condos['extwall']

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
2943,condominium,3.0,5651.0,condo townhouse,brick,2.0,1925.0,0.0,2179.0,2,0.0,2.0,0.0,0.0,2023-10-27,535000.0,2023.0,10.0

In [336]:
# Resetting the index
data_cleaned = data_cleaned.reset_index(drop=True)
data_cleaned

,proptype,district,nbhd,style,extwall,stories,year_built,rooms,finishedsqft,units,bdrms,fbath,hbath,lotsize,sale_date,sale_price,sale_year,sale_month
0,commercial,9.0,6202.0,office building - 1 story,concrete block,1.0,1981.0,0.0,12960.0,5,0.0,0.0,0.0,54885.0,2023-08-15,530000.0,2023.0,8.0
1,residential,9.0,40.0,cape cod,aluminum/vinyl,1.0,1942.0,7.0,1182.0,1,4.0,1.0,1.0,33541.0,2023-12-15,160000.0,2023.0,12.0
2,residential,9.0,40.0,ranch,fiber cement/hardiplank,1.0,2006.0,9.0,1880.0,1,3.0,2.0,0.0,10607.0,2023-08-31,387500.0,2023.0,8.0
3,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1980.0,6.0,1489.0,1,3.0,3.0,0.0,8640.0,2023-08-25,335000.0,2023.0,8.0
4,residential,9.0,40.0,ranch,aluminum/vinyl,1.0,1986.0,5.0,1209.0,1,3.0,1.0,1.0,7200.0,2023-06-20,250000.0,2023.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12907,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-11,125900.0,2022.0,3.0
12908,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1379.0,1,2.0,1.0,1.0,1.0,2022-10-28,150000.0,2022.0,10.0
12909,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,10.0,1100.0,1,4.0,1.0,1.0,1.0,2022-03-15,130000.0,2022.0,3.0
12910,condominium,13.0,5360.0,low rise 1-3 stories,brick,2.0,1974.0,5.0,1100.0,1,2.0,1.0,1.0,1.0,2022-12-30,123000.0,2022.0,12.0
12911,condominium,13.0,5360.0,low rise 1-3 stories,brick,1.0,1974.0,5.0,1141.0,1,2.0,1.0,1.0,1.0,2022-07-08,157500.0,2022.0,7.0

In [337]:
# Saving the cleaned data back to a CSV file

cleaned_file_path = 'Resources/clean_property_data.csv'
data_cleaned.to_csv(cleaned_file_path, index=False)